# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hybridmonitor_single <- function(y, y_Kp1, sig_level, z_alpha, B1, B2, B3, verbose, ncores) {
    .Call(`_energystuff_hybridmonitor_single`, y, y_Kp1, sig_level, z_alpha, B1, B2, B3, verbose, ncores)
}

hybridmonitor_multiple <- function(y, y_Kp1, sig_level, z_alpha, B1, B2, B3, T, verbose, ncores) {
    .Call(`_energystuff_hybridmonitor_multiple`, y, y_Kp1, sig_level, z_alpha, B1, B2, B3, T, verbose, ncores)
}

hybridmonitor_multiple_select_months <- function(y, y_Kp1_, sig_level, z_alpha_K, B1, B2, B3, T, m_idx, do_bonferroni, do_holm, do_hochberg, do_hommel, do_BH, do_BY, verbose, ncores) {
    .Call(`_energystuff_hybridmonitor_multiple_select_months`, y, y_Kp1_, sig_level, z_alpha_K, B1, B2, B3, T, m_idx, do_bonferroni, do_holm, do_hochberg, do_hommel, do_BH, do_BY, verbose, ncores)
}

